<?php
// application/layouts/scripts/layout.phtml
// Global layout

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>Example Poling <?php if (isset($this->title)) { ?> :: <?php echo
  $this->title; } ?></title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php if (isset($this->headContent)) echo $this->headContent; ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <strong>Polling Application!</strong>
    </div>
    <div id="header-navigation" style="float: right">
    <a href="<?php echo $this->url(
       array('controller'=>'index'),
       'default',
       true) ?>">Home</a>
    <a href="<?php echo $this->url(
       array('controller'=>'poll', 'action'=>'create'),
       'default',
       true) ?>">Create a Poll</a>
    </div>
</div>

<?php echo $this->layout()->content ?>

<div id="footer">
&copy; 2009 Quad341
</div>
</body>
</html>
